version: "3.7"

networks:
    mainNet: ~

# Careful, 'docker-compose down -v' will remove these volumes and associated datas, as well as 'docker volume prune'
#volumes:
#    data_mysql:

services:

  # redis://127.0.0.1:9633/0
  gql_slim_redis:
      image: redis:6
      container_name: gql_slim_redis
      hostname: "gql_slim_redis"
      privileged: true
      cap_add:
          - SYS_PTRACE
      ports:
          - 9633:6379 # host:container
      networks:
          - mainNet

  gql_slim_api:
      build:
        context: ./docker/images/php
        dockerfile: Dockerfile
      image: gql_slim_api:php7.3
      environment:
        - NODE_ENV=development
        - TERM=xterm-color
      cap_add:
        - SYS_PTRACE
      restart: on-failure
      hostname: gql_slim_api
      container_name: gql_slim_api
      ports:
        - "9632:9632"
      volumes:
        - type: "bind"
          source: "./"
          target: "/project"
      env_file:
        - .env
      networks:
          - mainNet
      command: "/run.sh"
      entrypoint: ""
      depends_on:
          - gql_slim_redis
      # extra_hosts:
      #     - "external_api:162.xx.xx.xx"

